name: okteto

# on:
#   schedule:
#     - cron: "25,26,27,28,29,30,31,32,33,34 * * * *"
   
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y upgrade
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: Clone source
      run: |
        pwd
        cd /home/runner
        wget https://github.com/okteto/okteto/releases/download/1.8.9/okteto-Linux-x86_64
        chmod +x ./okteto-Linux-x86_64
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
    - name: go go go
      run: |
        /home/runner/okteto-Linux-x86_64 login --token ${{ secrets.okteto_api_token }}
        /home/runner/okteto-Linux-x86_64 namespace chenshenyou
        wget https://raw.githubusercontent.com/chenshenyou/okteto-reboot/master/v2tls.yml
        kubectl replace --force -f /home/runner/v2tls.yml    
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /usr/local/bin/kubectl
